[workspace]
authors = ["ManifoldFR <wilson.jallet@polytechnique.org>"]
channels = ["conda-forge"]
name = "candlewick"
platforms = ["osx-64", "osx-arm64", "linux-64"]
version = "0.4.0"
license = "BSD-2-Clause"
license-file = "LICENSE"

[build-dependencies]
cmake = ">=3.26"
ninja = ">=1.12.1"
cxx-compiler = ">=1.9.0"
pkg-config = ">=0.29.2"
ccache = ">=4.9.1"

[dependencies]
sdl3 = ">=3.2.12,<4"
magic_enum = ">=0.9.7,<0.10"
entt = ">=3.15.0,<4"
nlohmann_json = ">=3.12.0,<4"
coal = ">=3.0.1,<4"
assimp = ">=5.4.3,<6"
eigenpy = ">=3.10.3,<4"
eigen = ">=3.4.0,<4"

[activation]
scripts = ["scripts/pixi/activation.sh"]

[tasks]
configure = { cmd = [
  "cmake",
  "-GNinja",
  "-B",
  "build",
  "-S",
  ".",
  "-DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX",
  "-DCMAKE_BUILD_TYPE=$CANDLEWICK_BUILD_TYPE",
  "-DBUILD_PYTHON_BINDINGS=$CANDLEWICK_WITH_PYTHON",
  "-DGENERATE_PYTHON_STUBS=OFF",
  "-DBUILD_PINOCCHIO_VISUALIZER=$CANDLEWICK_WITH_PINOCCHIO",
  "-DBUILD_TESTING=$CANDLEWICK_BUILD_TESTS",
] }
build = { cmd = "cmake --build build --target all", depends-on = ["configure"]}
clean = { cmd = "rm -rf build" }
doc = { cmd = "cmake --build build --target doc", depends-on = ["configure"] }

[feature.ffmpeg.dependencies]
ffmpeg = ">=7"

[feature.pinocchio.dependencies]
pinocchio = ">=3.5"

[feature.pinocchio.activation]
env = { CANDLEWICK_WITH_PINOCCHIO = "ON" }

[feature.test.dependencies]
gtest = "*"

[feature.test.activation]
env = { CANDLEWICK_BUILD_TESTS = "ON" }

[feature.doc.dependencies]
doxygen = "*"

[environments]
pinocchio = { features = ["pinocchio", "ffmpeg"] }
# test core
test = { features = ["test"] }
# test pinocchio, no ffmpeg
test-no-ffmpeg = { features = ["pinocchio", "test"] }
# test all (pinocchio + ffmpeg)
test-all = { features = ["pinocchio", "ffmpeg", "test"]}
# doc environment
doc = { features = ["doc", "default"] }
