name: gh-pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: prefix-dev/setup-pixi@v0.8.8
      with:
        cache: true
        environments: doc

    - name: Build documentation
      shell: bash -l {0}
      run: |
        pixi run -e doc doc

    - name: Upload to GitHub pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/doc/doxygen-html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4
      id: deployment
